### PR TITLE
[WIP] Refactor ITC code

### PR DESCRIPTION
**Pull request by bas-rustenburg**
For some of John's comments, please see bas-rustenburg/bayesian-itc#1

### CODE REVIEW

**Comment by jchodera** [comment]
Are we good to merge this?

**Comment by bas-rustenburg** [comment]
Possibly we can merge, but there is still some work to be done. I could open separate pull-request for later changes. 

Summarizing:

* `ITC.py` is restructured as a command line script that handles the calculations.
* Other stuff has been pushed into a library called `bayesianitc`. 

* `TwoComponentBindingModel` is working. 
* `CompetitiveBindingModel` doesn't work yet,

I also haven't validated yet whether all the unit conversions here and there are 100% correct. First priority was working code. So, use at your own risk.

Some plotting is broken.

**Comment by pgrinaway** [comment]
Maybe it would be better to merge this (since at least it runs now, right?), then fix the rest in separate pull requests? That way, the changes would be easier to discuss. Just a thought...

**Comment by bas-rustenburg** [comment]
Yes, that would be good. This is already one monster pull request. John, with your approval?

**Comment by bas-rustenburg** [comment]
Actually hold off for a second. Need to fix one more thing.

**Comment by bas-rustenburg** [comment]
There. Now it should be functional.

**Comment by bas-rustenburg** [comment]
I added the command I've been using to test to the readme for reference.

**Comment by jchodera** [comment]
+1 for merging now and fixing the rest later!

**Pull request merged**
