### PR TITLE
Combined Metropolis, RescalingStep samplers.

### PR DESCRIPTION
**Pull request by bas-rustenburg**
Running sampling for 1000000 steps to test.

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
Here is the data, fixing the bug so we're using both Metropolis and RescalingStep at once.

1,000,000 steps, 10000 burn-in, thinning period of 25:

sample-deltag
sample-deltah
sample-deltah_0
sample-ls
sample-p0
sample-sigma
sample-subtracted

**Comment by jchodera** [comment]
How does this compare to omitting RescalingStep?

**Comment by bas-rustenburg** [comment]
@jchodera see #54, I added the comparison there.

**Comment by bas-rustenburg** [comment]
Switched back to using Metropolis only, but leaving the fixed implementation of RescalingStep for if we change our minds.

**Pull request merged**
