### PR TITLE
[Suggestion] Some code remodelling to improve modularity and readability

### PR DESCRIPTION
**Pull request by bas-rustenburg**

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
I was playing around with some of the code in TwoComponentBindingModel and thinking of ways to improve modularity. I wonder if this is more, or less readable than the current form.

**Comment by bas-rustenburg** [comment]
Diff looks kinda messy, probably want to look at the [file](https://github.com/bas-rustenburg/bayesian-itc/blob/5a94224ebdff1fa4b508356934d15ee66fb52679/bitc/models.py) on its own.

**Comment by bas-rustenburg** [comment]
Here is something interesting.

I took a look at the different step methods for MCMC. Here is the host concentration, estimated at 1.0157 mM in this particular experiment (I just picked a host-guest titration at random from one of our previous sets of experiments).

Settings:
Using the TwoComponentBindingModel about 320000 iterations (I stopped it at around 16% of 2000000) 10000 burn in iterations and a thinning period of 25. Not sure how good those settings are but there is quite a striking difference.

Using the RescalingStep:
sample-ls
Note that the value on the y-axis is offset by 1.0124
Using a default pymc Metropolis step:
sample-ls

**Comment by bas-rustenburg** [comment]
Opened an issue for discussion.

**Comment by jchodera** [comment]
Good catch. Let's use MetropolisStep for now. I think eventually we want to
use both!

**Comment by pgrinaway** [comment]
Looking good, I like the base classes

**Comment by bas-rustenburg** [comment]
@jchodera, could you take a quick look at this before I merge?

**Comment by jchodera** [comment]
Looks great!

**Pull request merged**
